<?php
class BudgetController extends Controller {
    public function index(): void {Auth::requireLogin();$uid=Auth::user()['id'];$budgets=Budget::all($uid);$details=[];foreach($budgets as $b)$details[$b['id']]=Budget::expenses((int)$b['id'],$uid);$this->render('budgets/index',['budgets'=>$budgets,'details'=>$details,'csrf'=>$this->csrf()]);}
    public function save(): void {Auth::requireLogin();$this->verifyCsrf();$d=['name'=>trim($_POST['name']),'category'=>trim($_POST['category']),'limit_amount'=>(float)$_POST['limit_amount'],'period'=>$_POST['period'],'initial_spent'=>(float)($_POST['initial_spent']??0)];if($d['name']&&$d['limit_amount']>0){Budget::create(Auth::user()['id'],$d);$this->flash('success','Presupuesto creado.');}else{$this->flash('error','Completa el presupuesto.');}$this->redirect('index.php?url=budgets');}
    public function edit(): void {Auth::requireLogin();$this->verifyCsrf();Budget::update((int)$_POST['id'],Auth::user()['id'],['name'=>trim($_POST['name']),'category'=>trim($_POST['category']),'limit_amount'=>(float)$_POST['limit_amount'],'period'=>$_POST['period'],'initial_spent'=>(float)$_POST['initial_spent']]);$this->flash('success','Presupuesto actualizado.');$this->redirect('index.php?url=budgets');}
    public function delete(): void {Auth::requireLogin();$this->verifyCsrf();Budget::delete((int)$_POST['id'],Auth::user()['id']);$this->flash('success','Presupuesto eliminado.');$this->redirect('index.php?url=budgets');}
    public function expense(): void {Auth::requireLogin();$this->verifyCsrf();Budget::addExpense((int)$_POST['budget_id'],Auth::user()['id'],['amount'=>(float)$_POST['amount'],'date'=>$_POST['date'],'description'=>trim($_POST['description']??'')]);$this->flash('success','Gasto agregado y descontado del presupuesto.');$this->redirect('index.php?url=budgets');}
    public function editExpense(): void {Auth::requireLogin();$uid=Auth::user()['id'];$id=(int)($_GET['id']??$_POST['id']??0); if($_SERVER['REQUEST_METHOD']==='POST'){ $this->verifyCsrf(); Budget::updateExpense($id,$uid,['amount'=>(float)$_POST['amount'],'date'=>$_POST['date'],'description'=>trim($_POST['description']??'')]); $this->flash('success','Gasto actualizado.'); $this->redirect('index.php?url=budgets'); } $st=Database::get()->prepare('SELECT e.* FROM budget_expenses e JOIN budgets b ON b.id=e.budget_id WHERE e.id=? AND b.user_id=?');$st->execute([$id,$uid]);$expense=$st->fetch();if(!$expense){$this->flash('error','Gasto no encontrado.');$this->redirect('index.php?url=budgets');}$this->render('budgets/edit_expense',['expense'=>$expense,'csrf'=>$this->csrf()]);}
    public function deleteExpense(): void {Auth::requireLogin();$this->verifyCsrf();Budget::deleteExpense((int)$_POST['id'],Auth::user()['id']);$this->flash('success','Gasto eliminado.');$this->redirect('index.php?url=budgets');}
}
