<?php
class GoalController extends Controller {
    public function index(): void {Auth::requireLogin();$uid=Auth::user()['id'];$this->render('goals/index',['goals'=>Goal::all($uid),'totals'=>Goal::totals($uid),'csrf'=>$this->csrf()]);}
    public function save(): void {Auth::requireLogin();$this->verifyCsrf();$uid=Auth::user()['id'];$d=['name'=>trim($_POST['name']),'target_amount'=>(float)$_POST['target_amount'],'initial_amount'=>(float)($_POST['initial_amount']??0),'deadline'=>$_POST['deadline']??''];if($d['name']&&$d['target_amount']>0){Goal::create($uid,$d);$this->flash('success','Meta creada.');}else{$this->flash('error','Completa el nombre y monto objetivo.');}$this->redirect('index.php?url=goals');}
    public function edit(): void {Auth::requireLogin();$this->verifyCsrf();$uid=Auth::user()['id'];$id=(int)$_POST['id'];$current=Goal::find($id,$uid); Goal::update($id,$uid,['name'=>trim($_POST['name']),'target_amount'=>(float)$_POST['target_amount'],'initial_amount'=>(float)($current['initial_amount']??0),'deadline'=>$_POST['deadline']??'']);$this->flash('success','Meta actualizada.');$this->redirect('index.php?url=goals');}
    public function delete(): void {Auth::requireLogin();$this->verifyCsrf();Goal::delete((int)$_POST['id'],Auth::user()['id']);$this->flash('success','Meta eliminada.');$this->redirect('index.php?url=goals');}
    public function contribution(): void {Auth::requireLogin();$this->verifyCsrf();Goal::addContribution((int)$_POST['goal_id'],Auth::user()['id'],['amount'=>(float)$_POST['amount'],'date'=>$_POST['date'],'note'=>trim($_POST['note']??'')]);$this->flash('success','Abono registrado.');$this->redirect('index.php?url=goals');}
    public function editContribution(): void {Auth::requireLogin();$uid=Auth::user()['id'];$id=(int)($_GET['id']??$_POST['id']??0); if($_SERVER['REQUEST_METHOD']==='POST'){ $this->verifyCsrf(); Goal::updateContribution($id,$uid,['amount'=>(float)$_POST['amount'],'date'=>$_POST['date'],'note'=>trim($_POST['note']??'')]); $this->flash('success','Abono actualizado.'); $this->redirect('index.php?url=goals'); } $st=Database::get()->prepare('SELECT c.* FROM goal_contributions c JOIN savings_goals g ON g.id=c.goal_id WHERE c.id=? AND g.user_id=?');$st->execute([$id,$uid]);$con=$st->fetch();if(!$con){$this->flash('error','Abono no encontrado.');$this->redirect('index.php?url=goals');}$this->render('goals/edit_contribution',['con'=>$con,'csrf'=>$this->csrf()]);}
    public function deleteContribution(): void {Auth::requireLogin();$this->verifyCsrf();Goal::deleteContribution((int)$_POST['id'],Auth::user()['id']);$this->flash('success','Abono eliminado.');$this->redirect('index.php?url=goals');}
}
