<?php
class Goal {
    public static function all(int $uid): array { $st=Database::get()->prepare('SELECT g.*, COALESCE(SUM(c.amount),0) saved FROM savings_goals g LEFT JOIN goal_contributions c ON c.goal_id=g.id WHERE g.user_id=? GROUP BY g.id ORDER BY g.deadline IS NULL,g.deadline'); $st->execute([$uid]); return $st->fetchAll(); }
    public static function find(int $id,int $uid): ?array { $st=Database::get()->prepare('SELECT g.*,COALESCE(SUM(c.amount),0) saved FROM savings_goals g LEFT JOIN goal_contributions c ON c.goal_id=g.id WHERE g.id=? AND g.user_id=? GROUP BY g.id'); $st->execute([$id,$uid]); return $st->fetch() ?: null; }
    public static function create(int $uid,array $d): int { $db=Database::get(); $db->beginTransaction(); $st=$db->prepare('INSERT INTO savings_goals(user_id,name,target_amount,initial_amount,deadline) VALUES(?,?,?,?,?)'); $st->execute([$uid,$d['name'],$d['target_amount'],$d['initial_amount'],$d['deadline'] ?: null]); $id=(int)$db->lastInsertId(); if((float)$d['initial_amount']>0){$x=$db->prepare('INSERT INTO goal_contributions(goal_id,amount,date,note) VALUES(?,?,CURDATE(),?)');$x->execute([$id,$d['initial_amount'],'Aporte inicial']);} $db->commit(); return $id; }
    public static function update(int $id,int $uid,array $d): void { $st=Database::get()->prepare('UPDATE savings_goals SET name=?,target_amount=?,initial_amount=?,deadline=? WHERE id=? AND user_id=?'); $st->execute([$d['name'],$d['target_amount'],$d['initial_amount'],$d['deadline'] ?: null,$id,$uid]); }
    public static function delete(int $id,int $uid): void { $st=Database::get()->prepare('DELETE FROM savings_goals WHERE id=? AND user_id=?'); $st->execute([$id,$uid]); }
    public static function contributions(int $goal,int $uid): array { $st=Database::get()->prepare('SELECT c.* FROM goal_contributions c JOIN savings_goals g ON g.id=c.goal_id WHERE c.goal_id=? AND g.user_id=? ORDER BY c.date DESC,c.id DESC'); $st->execute([$goal,$uid]); return $st->fetchAll(); }
    public static function addContribution(int $goal,int $uid,array $d): void { $st=Database::get()->prepare('INSERT INTO goal_contributions(goal_id,amount,date,note) SELECT ?,?,?,? FROM savings_goals WHERE id=? AND user_id=?'); $st->execute([$goal,$d['amount'],$d['date'],$d['note'] ?: null,$goal,$uid]); }
    public static function updateContribution(int $id,int $uid,array $d): void { $st=Database::get()->prepare('UPDATE goal_contributions c JOIN savings_goals g ON g.id=c.goal_id SET c.amount=?,c.date=?,c.note=? WHERE c.id=? AND g.user_id=?'); $st->execute([$d['amount'],$d['date'],$d['note'] ?: null,$id,$uid]); }
    public static function deleteContribution(int $id,int $uid): void { $st=Database::get()->prepare('DELETE c FROM goal_contributions c JOIN savings_goals g ON g.id=c.goal_id WHERE c.id=? AND g.user_id=?'); $st->execute([$id,$uid]); }
    public static function totals(int $uid): array { $st=Database::get()->prepare('SELECT COALESCE(SUM(target_amount),0) target,COALESCE(SUM(saved),0) saved FROM (SELECT g.id,g.target_amount,COALESCE(SUM(c.amount),0) saved FROM savings_goals g LEFT JOIN goal_contributions c ON c.goal_id=g.id WHERE g.user_id=? GROUP BY g.id) x'); $st->execute([$uid]); $r=$st->fetch(); return $r ?: ['target'=>0,'saved'=>0]; }
}
